### ISSUE TITLE
Cannot add dependency 'org.scala-lang#scala-compiler;2.11.7' to configuration 'ensime-internal'

### ISSUE THREAD

**Issue by VlachJosef** [ensime/ensime-sbt#145]
I'm facing the same problem as https://github.com/ensime/ensime-sbt/issues/140, but I'm not aware of any problem with my configuration. I've put together minimal example for reproducing https://github.com/VlachJosef/ensime-sbt-issue

In my project I'm using https://github.com/sbt/sbt-scalabuff which is not a particularly up-to-date sbt plugin.

When I run `gen-ensime` with `addSbtPlugin("org.ensime" % "ensime-sbt" % "0.2.3")` in my `~/.sbt/0.13/plugins/plugins.sbt` everything is ok, but as soon as I use `addSbtPlugin("org.ensime" % "ensime-sbt" % "0.3.2")` I keep getting this error when running `gen-ensime`:
```
[main]> gen-ensime
[info] ENSIME update. Please vote for https://github.com/sbt/sbt/issues/2266
[info] Updating {file:/Users/pepa/develop-ensime/ensime-sbt-issue/}main...
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[error] (*:update) java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.11.7' to configuration 'ensime-internal' of module using.scalabuff#ensime-sbt-issue_2.11;0.1-SNAPSHOT because this configuration doesn't exist!
[error] Missing task key: Runs the aggregated UpdateReport for `update' and `updateClassifiers' respectively.
java.lang.IllegalArgumentException
	at org.ensime.CommandSupport$class.fail(EnsimePlugin.scala:593)
	at org.ensime.EnsimePlugin$.fail(EnsimePlugin.scala:116)
	at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:608)
	at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:608)
	at scala.Option.getOrElse(Option.scala:120)
	at org.ensime.CommandSupport$RichTaskKey.run(EnsimePlugin.scala:608)
	at org.ensime.EnsimePlugin$$anonfun$genEnsime$1.apply(EnsimePlugin.scala:249)
	at org.ensime.EnsimePlugin$$anonfun$genEnsime$1.apply(EnsimePlugin.scala:220)
	at sbt.Command$$anonfun$sbt$Command$$apply1$1$$anonfun$apply$6.apply(Command.scala:71)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.IllegalArgumentException
[error] Use 'last' for the full log.
```
But others commands are broken also. For example when running `clean` I'm getting:
```
[main]> clean
[trace] Stack trace suppressed: run 'last *:clean' for the full output.
[error] (*:clean) java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.11.7' to configuration 'ensime-internal' of module using.scalabuff#ensime-sbt-issue_2.11;0.1-SNAPSHOT because this configuration doesn't exist!
[error] Total time: 0 s, completed Jan 6, 2016 11:34:59 AM
```

**Comment by fommil** [comment]
thanks for the minimal reproduction! My initial guess is that your build definition is actually subtely broken but I'll have a look tonight.

BTW, are you coming on the 16th Jan to the next Hack the Tower? :smile:

**Comment by fommil** [comment]
yup this is dodgy https://github.com/VlachJosef/ensime-sbt-issue/blob/master/project/Build.scala#L7

```scala
lazy val root = Project("main", file("."), settings = Defaults.defaultSettings ++ scalabuffSettings).configs(ScalaBuff)
```

what I believe you meant to say was

```scala
override lazy val rootProject = ...
```

can you please report this upstream, as I realise this is this recommendation and **it is wrong**.

Just because the project is called `root` doesn't mean it *is* the root project. What is happening here is a module called `root` is being created and then an implicit root project is being created with a different version of scala and no scalabuffSettings.

**Comment by fommil** [comment]
(please reopen if that doesn't fix it, probably we should add it to the `sbt-test` suite if it is still an issue)

**Comment by VlachJosef** [comment]
Hack the Tower on the 16th Jan? I'll be there :)

**Comment by VlachJosef** [comment]
If I try override `rootProject` in `sbt.Build` which type is `Option[Project]` like this
```scala
override lazy val rootProject = Some(Project("main", file("."), settings = Defaults.defaultSettings ++ scalabuffSettings).configs(ScalaBuff))
```
I'll get
```
java.lang.RuntimeException: No projects defined in build unit /Users/pepa/develop-ensime/ensime-sbt-issue
```

**Comment by VlachJosef** [comment]
Can you please reopen the issue, as I can't do it.

**Comment by fommil** [comment]
maybe leave it as it is and add this line

```scala
override lazy val rootProject = root
```

**Comment by VlachJosef** [comment]
by doing so I'm getting back to original error: `Cannot add dependency 'org.scala-lang#scala-compiler;2.11.7' to configuration 'ensime-internal' `

**Comment by fommil** [comment]
interesting. I'll have a look. Please ping at the weekend if I forget.

**Comment by VlachJosef** [comment]
Thanks for looking into this. I'll remind you at the weekend in case it is not solved by then.

**Comment by fommil** [comment]
@VlachJosef change your config to this

```
  lazy val root = Project("root", file(".")).configs(ScalaBuff).settings(scalabuffSettings)
```

the way you're doing it, I think you're bypassing the standard sbt plugins settings loading.

**Comment by VlachJosef** [comment]
@fommil that works, great. Thank you.

**Comment by jmcejuela** [comment]
This was very useful, thank you ^.^

the key for me was the part of: `.settings(...yourSettings...)` instead of doing the previous, and I guess deprecated, `settings = Defaults.defaultSettings ++ yourSettings`

**Comment by brennovich** [comment]
I solved this by explicitly adding `EnsimePlugin.projectSettings` into my settings:

``` scala
.settings(mySettings ++ EnsimePlugin.projectSettings)
```

It can be also globally solved by adding a `~/.sbt/0.13/global.sbt`:

``` scala
import org.ensime.EnsimePlugin

EnsimePlugin.projectSettings
```
