### ISSUE TITLE
False meta-circular depencency on scala?

### ISSUE THREAD

**Issue by losvald** [ensime/ensime-sbt#157]
I'm trying to run "sbt gen-ensime" on the source of scala itself, and here is what I get:

	[error] a module is not authorized to depend on itself: org.scala-lang#scala-library;2.11.7
	java.lang.IllegalArgumentException: a module is not authorized to depend on itself: org.scala-lang#scala-library;2.11.7
		at org.apache.ivy.core.resolve.IvyNodeCallers.addCaller(IvyNodeCallers.java:167)
		at org.apache.ivy.core.resolve.IvyNode.addCaller(IvyNode.java:1076)
		at org.apache.ivy.core.resolve.IvyNode.getDependencies(IvyNode.java:369)
		at org.apache.ivy.core.resolve.VisitNode.getDependencies(VisitNode.java:313)
		at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:792)
		at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:722)
		at org.apache.ivy.core.resolve.ResolveEngine.getDependencies(ResolveEngine.java:594)
		at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:234)
		at org.apache.ivy.Ivy.resolve(Ivy.java:517)
		at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:282)
		at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
		at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
		at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
		at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
		at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
		at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
		at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
		at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
		at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
		at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
		at xsbt.boot.Using$.withResource(Using.scala:10)
		at xsbt.boot.Using$.apply(Using.scala:9)
		at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
		at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
		at xsbt.boot.Locks$.apply0(Locks.scala:31)
		at xsbt.boot.Locks$.apply(Locks.scala:28)
		at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
		at sbt.IvySbt.withIvy(Ivy.scala:127)
		at sbt.IvySbt.withIvy(Ivy.scala:124)
		at sbt.IvySbt$Module.withModule(Ivy.scala:155)
		at sbt.IvyActions$.updateEither(IvyActions.scala:168)
		at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
		at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
		at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
		at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
		at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
		at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
		at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
		at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
		at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
		at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
		at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
		at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
		at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
		at sbt.std.Transform$$anon$4.work(System.scala:63)
		at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
		at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
		at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
		at sbt.Execute.work(Execute.scala:235)
		at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
		at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
		at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
		at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
		at java.util.concurrent.FutureTask.run(FutureTask.java:262)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
		at java.util.concurrent.FutureTask.run(FutureTask.java:262)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:745)
	[error] (library/*:update) java.lang.IllegalArgumentException: a module is not authorized to depend on itself: org.scala-lang#scala-library;2.11.7
	[error] Missing task key: Runs the aggregated UpdateReport for `update' and `updateClassifiers' respectively.
	java.lang.IllegalArgumentException
		at org.ensime.CommandSupport$class.fail(EnsimePlugin.scala:593)
		at org.ensime.EnsimePlugin$.fail(EnsimePlugin.scala:116)
		at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:608)
		at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:608)
		at scala.Option.getOrElse(Option.scala:120)
		at org.ensime.CommandSupport$RichTaskKey.run(EnsimePlugin.scala:608)
		at org.ensime.EnsimePlugin$$anonfun$genEnsime$1.apply(EnsimePlugin.scala:249)
		at org.ensime.EnsimePlugin$$anonfun$genEnsime$1.apply(EnsimePlugin.scala:220)
		at sbt.Command$$anonfun$sbt$Command$$apply1$1$$anonfun$apply$6.apply(Command.scala:71)
		at sbt.Command$.process(Command.scala:93)
		at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
		at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
		at sbt.State$$anon$1.process(State.scala:184)
		at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
		at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
		at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
		at sbt.MainLoop$.next(MainLoop.scala:98)
		at sbt.MainLoop$.run(MainLoop.scala:91)
		at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
		at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
		at sbt.Using.apply(Using.scala:24)
		at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
		at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
		at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
		at sbt.MainLoop$.runLogged(MainLoop.scala:24)
		at sbt.StandardMain$.runManaged(Main.scala:53)
		at sbt.xMain.run(Main.scala:28)
		at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
		at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
		at xsbt.boot.Launch$.run(Launch.scala:109)
		at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
		at xsbt.boot.Launch$.launch(Launch.scala:117)
		at xsbt.boot.Launch$.apply(Launch.scala:18)
		at xsbt.boot.Boot$.runImpl(Boot.scala:41)
		at xsbt.boot.Boot$.main(Boot.scala:17)
		at xsbt.boot.Boot.main(Boot.scala)
	[error] java.lang.IllegalArgumentException
	[error] Use 'last' for the full log.

IMHO, this is a bug since I'm not running `sbt` with the scala compiled from the source I'm trying to analyze with ENSIME but rather the one installed on my machine. However, `ensime-sbt` seems to be fooled in this case.

To reproduce with version 0.3.2 of ensime:

	git clone --depth 1 --single-branch -b 2.11.x https://github.com/scala/scala.git && cd scala && sbt gen-ensime

**Comment by fommil** [comment]
1. You've not given a reproduction
2. You're running an old version

I'm getting inundated with bug reports not following the basic requirements check as per the Getting Help section on ensime.org so I'm aggressively closing tickets of this nature for my own sanity.

**Comment by losvald** [comment]
Sorry, I forgot to say my sbt version is 0.13.9 (latest). I did try again with the latest release (0.3.3), after cleaning ivy2 cache for ensime, but the problem is still there!

(Note the rest of the Troubleshooting guide you mentioned does not apply as we are talking about the bug in the process of *creating* .ensime configuration and there is no usage of editor whatsoever.)

If you really think the bug is specific to my (mis)configured environment, would you mind running the above command and pasting your output, please?

(Note it does more than checking the project, it also runs `sbt gen-ensime`.)

**Comment by fommil** [comment]
oh come on, the `scala/scala` sbt build is insane!!! That's a bit unfair :stuck_out_tongue:

There is a custom `.ensime` file for `scala/scala` documented in the code tree, I recommend you use that.
