### ISSUE TITLE
Some keys were defined with the same name but different types: 'compileOnly' (Boolean, sbt.InputTask[Unit])

### ISSUE THREAD

**Issue by bfil** [ensime/ensime-sbt#194]
Just upgraded from `ensime-sbt` version `0.4.0` to `sbt-ensime` `0.5.0` and I'm getting the following error:

```
java.lang.RuntimeException: Some keys were defined with the same name but different types: 'compileOnly' (Boolean, sbt.InputTask[Unit])
	at scala.sys.package$.error(package.scala:27)
	at sbt.Index$.stringToKeyMap0(EvaluateConfigurations.scala:296)
	at sbt.Index$.stringToKeyMap(EvaluateConfigurations.scala:287)
	at sbt.Load$.structureIndex(Load.scala:190)
	at sbt.Load$.apply(Load.scala:147)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:492)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:492)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:54)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] Some keys were defined with the same name but different types: 'compileOnly' (Boolean, sbt.InputTask[Unit])
```

It looks like compileOnly is define as a task as well as a setting key.

**Comment by fommil** [comment]
Can you please give a reproduction in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also a good starting point. We are more than happy to help you turn it into an automated test, and discuss ideas on how to fix it. Read the http://ensime.org/contributing guide for more information.

We close tickets that look like a known issue or don't provide the details requested by the template, but it's not the end of the conversation and we will open it up again when there is enough information to go on. This is to improve the quality of our issue tracker and to make it easier for contributors to help.

We will reopen this ticket if you can confirm it is a bug by giving us a **detailed** reproduction. Please read the http://ensime.org/getting_help guide to understand the steps that are required prior to submitting a bug report.

**Comment by bfil** [comment]
Closing the issue seems like a very bad practice to me, considering there are no steps involved in order to reproduce an SBT plugin compilation issue, it just does not compile my projects anymore.

I'll give you the details anyway, I've changed:

`addSbtPlugin("org.ensime" % "ensime-sbt" % "0.4.0")`

to:

`addSbtPlugin("org.ensime" % "sbt-ensime" % "0.5.0")`

I have no custom settings or anything else, I've provided you with the stack trace, I've suggested what the issue can be: since in the plugin code I can see that both a setting key and a setting task have been defined using the same name. SBT does not namespace keys, so it looks like a bug to me.

I just have it configured in my global plugins under `~/.sbt/0.13/plugins/plugins.sbt`.

What other kind of details would you need?

**Comment by fommil** [comment]
your project, your sbt settings

**Comment by fommil** [comment]
I don't see where we have a `compileOnly` `Setting`

**Comment by bfil** [comment]
I found out where it conflicts: https://github.com/sbt/sbt-aspectj/blob/master/src/main/scala/com/typesafe/sbt/SbtAspectj.scala#L32

I guess it might be worth considering namespacing all the keys with a prefix like most plugins do:

`ensimeCompileOnly` instead of `compileOnly`?

I guess that the fact that sbt does not namespace keys is just something every plugin should accept to live with? I know it's kind of ugly to prefix all the keys, but all plugins follow the same pattern.

**Comment by fommil** [comment]
I don't understand how this clashes, theirs is `compile-only` and ours is `compileOnly`.

Given that ours is doing the intuitive thing for the naming convention (c.f. `testOnly`) I'm pretty sure it's for aspectj to change their setting name.

Can you perhaps ask on the `sbt/sbt` gitter channel for options here? Plugin authors can't be expected to prefix everything everytime a collision comes up like this.

**Comment by bfil** [comment]
Unfortunately that's how most of the plugins do it, just take a look at the keys of all the native packager modules:

https://github.com/sbt/sbt-native-packager/tree/master/src/main/scala/com/typesafe/sbt/packager

Or `sbt-scoverage`:

https://github.com/scoverage/sbt-scoverage/blob/master/src/main/scala/scoverage/ScoverageKeys.scala

I don't think there is a way around it?

**Comment by fommil** [comment]
@bfil can you please create a reproduction, I can see the potential for a collision here but it needs to be explicit. The `compile-only` scripted test would seem to be a good place for this https://github.com/ensime/ensime-sbt/tree/master/src/sbt-test/ensime-sbt/compile-only and from there we can help you to fix any bugs that are discovered.

I am of the opinion that `sbt-aspectj` should change their (poorly named) `Setting` since we are using the name for something that is both idiomatic and expected by any user. The ideal situation here is if you could document a workaround to be implemented in your projects, that we can share as an FAQ. The concept of "compiling only these files" is independent of ENSIME and doesn't warrant a namespace prefix.

**Comment by fommil** [comment]
Something I was thinking of that could be a workaround is to split `EnsimePlugin` into two plugins, the second called `EnsimeExtrasPlugin` which would contain non-essential tasks to help developer workflow.

@bfil I'll still need a reproduction from you on this, e.g. minimal project displaying the problems. Flagging for close if we don't hear back in a week or so.

**Comment by bfil** [comment]
Ok, I'll try my best to code up a reproduction asap, thanks.

**Comment by bfil** [comment]
Here it is: https://github.com/bfil/sbt-ensime-bug

**Comment by vertexclique** [comment]
I have run into same problem.

**Comment by fommil** [comment]
@bfil can we expect a PR to address this from you? It may be some time before I have another reason to split the plugin into two parts.

I also hope you have raised the issue with the aspectj plugin authors and asked them to namespace their setting. Any ensime workaround will be about empowering users to disable the functionality as we do not plan to rename this `Task`: it is idiomatic with the usage of `test` vs `testOnly` for `compile` and `compileOnly`.

**Comment by fommil** [comment]
requested here https://github.com/sbt/sbt-aspectj/issues/29

**Comment by fommil** [comment]
I've had a change of heart on this one, I'll accept a PR to namespace all our commands. No need for a test for this.
