### ISSUE TITLE
java.lang.NoSuchMethodError: scalaz.EitherT.orElse(Lscala/Function0;Lscalaz/Bind;)Lscalaz/EitherT;

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#277]
discovered by @dragos we are incompatible with sbt-eclipse.

This is actually because of incompatible scalaz versions and if you would like to fix it, please help fix the upstream report https://github.com/alexarchambault/coursier/issues/25

```
[error] ({.}/*:ensimeScalaJars) java.lang.NoSuchMethodError: scalaz.EitherT.orElse(Lscala/Function0;Lscalaz/Bind;)Lscalaz/EitherT;
[error] Missing task key: ensimeScalaJars
java.lang.IllegalArgumentException
    at org.ensime.CommandSupport$.org$ensime$CommandSupport$$fail(EnsimePlugin.scala:613)
    at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:628)
    at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:628)
    at scala.Option.getOrElse(Option.scala:120)
    at org.ensime.CommandSupport$RichTaskKey.run(EnsimePlugin.scala:628)
```

**Comment by fommil** [comment]
workaround is to 1) remove the other plugin, or 2) disable the new server jar resolver and put this in a `ensime.sbt`

```
    ensimeScalaJars := Nil
    ensimeScalaProjectJars := Nil
    ensimeServerJars := Nil
    ensimeServerProjectJars := Nil
```

but you'll also lose the ability to use the ensime repl or use assembly jars.
