### ISSUE TITLE
NoSuchMethodError when upgrading from coursier M14 to M15

### ISSUE THREAD

**Issue by timcharper** [ensime/ensime-sbt#280]
It looks like ensime depends on something that coursier that broke in M15. Getting the following stack trace with coursier M15 and ensime-sbt `1.12.0`:

```
java.lang.NoSuchMethodError: coursier.maven.MavenRepository$.apply(Ljava/lang/String;Lscala/Option;ZLscala/Option;)Lcoursier/maven/MavenRepository;
	at org.ensime.EnsimeCoursierPlugin$$anonfun$buildSettings$2.apply(EnsimeCoursierPlugin.scala:42)
	at org.ensime.EnsimeCoursierPlugin$$anonfun$buildSettings$2.apply(EnsimeCoursierPlugin.scala:40)
	at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:609)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.NoSuchMethodError: coursier.maven.MavenRepository$.apply(Ljava/lang/String;Lscala/Option;ZLscala/Option;)Lcoursier/maven/MavenRepository;
```

**Comment by fommil** [comment]
known issue

**Comment by timcharper** [comment]
Where? I searched and didn't see it.

**Comment by timcharper** [comment]
Oh, I see the pull request: https://github.com/ensime/ensime-sbt/pull/279

**Comment by fommil** [comment]
it's got a particularly nasty upgrade path...

**Comment by timcharper** [comment]
... indeed. The bleeding edge cuts both ways.
