### ISSUE TITLE
Not working with Scala 2.12.1 and sbt 0.13.13

### ISSUE THREAD

**Issue by alex3kov** [ensime/ensime-sbt#294]
Reproduction:
```sh
echo 'addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.4")' > ~/.sbt/0.13/plugins/plugins.sbt
git clone https://github.com/alex3kov/scala-helloworld.git
cd scala-helloworld
sbt
[info] Loading global plugins from /home/username/.sbt/0.13/plugins
[info] Set current project to scala-helloworld (in build file:/home/username/code/scala-helloworld/)
> ensimeConfig
[info] ENSIME update.
[info] Resolving jline#jline;2.14.1 ...
[error] ({.}/*:ensimeServerJars) failed to resolve (Dependency(org.ensime:server_2.12,1.0.0,compile,Set(),Attributes(jar,),false,true),List(not found: https://repo1.maven.org/maven2/org/ensime/server_2.12/1.0.0/server_2.12-1.0.0.pom, not found: https://oss.sonatype.org/content/repositories/snapshots/org/ensime/server_2.12/1.0.0/server_2.12-1.0.0.pom))
[error] Missing task key: ensimeServerJars
java.lang.IllegalArgumentException
	at org.ensime.CommandSupport$.org$ensime$CommandSupport$$fail(EnsimePlugin.scala:614)
	at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:629)
	at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:629)
	at scala.Option.getOrElse(Option.scala:120)
	at org.ensime.CommandSupport$RichTaskKey.run(EnsimePlugin.scala:629)
	at org.ensime.EnsimePlugin$$anonfun$ensimeConfig$1.apply(EnsimePlugin.scala:233)
	at org.ensime.EnsimePlugin$$anonfun$ensimeConfig$1.apply(EnsimePlugin.scala:196)
	at sbt.Command$$anonfun$sbt$Command$$apply1$1$$anonfun$apply$6.apply(Command.scala:71)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.IllegalArgumentException
[error] Use 'last' for the full log.
```

**Comment by fommil** [comment]
Troubleshooting. Always use troubleshooting.

**Comment by alex3kov** [comment]
Okay, I looked at [this](https://ensime.github.io/build_tools/sbt/#troubleshooting), went through [FAQ tickets](https://github.com/ensime/ensime-sbt/issues?q=label%3AFAQ), the only similarly looking issue is #276, so I did `rm -rf ~/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots` - didn't help. I also should've mentioned that everything works well at 2.11.8.

**Comment by fommil** [comment]
ensime-server recent tickets

**Comment by alex3kov** [comment]
So not troubleshooting, huh?  
Could you clarify a bit please - do you mean #1673 aka "everything is broken", or something else? There are plenty of tickets, none seem directly related.

**Comment by fommil** [comment]
Troubleshooting leads you to search recent activity on server tickets, wherein you find this very actively discussed ticket https://github.com/ensime/ensime-server/issues/1414

The troubleshooting guide recommends that you use gitter not github, because that way everybody in the ensime userbase can respond, not just me (I'm the only person actively responding to the issue tracker and it is reserved for dev, not support)

1673 has absolutely no relevance for releases

**Comment by apauzies** [comment]
@alex3kov 

I created this file: ~/.sbt/0.13/global.sbt
with:
import org.ensime.EnsimeCoursierKeys._
ensimeServerVersion in ThisBuild := "2.0.0-SNAPSHOT"

And changed sbt-ensime to version 1.12.8 and it worked.

**Comment by fommil** [comment]
Glad to hear that following the documentation worked for you.
