### ISSUE TITLE
Not able to debug application

### ISSUE THREAD

**Issue by elbaulp** [ensime/ensime-sbt#297]
Hi, when I try to debug an app, the only command that works to control the execution of the debugger is `C-c C-d c` (continue), If I want to step the debugger to the next line (`C-c C-d n`) nothing happens. I've created a minimal project here https://github.com/algui91/ensimedebug

### Steps to reproduce

```bash
$ cd hello
$ sbt
> ensimeConfig
[info] ENSIME update.
[info] Resolving jline#jline;2.12.1 ...
[info] ENSIME processing root (Hello)
[warn] No Java sources detected in /opt/icedtea-bin-3.2.0 (your ENSIME experience will not be as good as it could be.)
> debugging
[warn] Enabling debugging for all forked processes on port 5005
[info] Only one process can use the port and it will await a connection before proceeding.
[info] Set current project to Hello (in build file:/home/hkr/Desarrollo/scala/TDD/hello/)
> ensimeRunDebug example.Hello
[info] Running example.Hello 
[info] Listening for transport dt_socket at address: 5005
```

Now, in emacs:

1.  open the project, run `M-x ensime`.

The output of *ENSIME*-hello:

```
12:18:09.678 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
12:18:09.692 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
12:18:09.696 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
12:18:09.743 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
12:18:09.813 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:34428
12:18:09.818 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 34428
12:18:09.828 INFO  None o.e.s.PortUtil$ - creating port file: /home/hkr/Desarrollo/scala/TDD/hello/.ensime_cache/port
12:18:10.880 DEBUG None o.e.f.FileWatchService - init watcher
12:18:10.893 DEBUG None o.e.f.FileWatchService - start a background monitoring thread
12:18:10.909 DEBUG None o.e.f.FileWatchService - start monitoring WatchService events
12:18:10.943 DEBUG None o.e.f.FileWatchService - init watcher
12:18:10.945 DEBUG None o.e.f.FileWatchService - start a background monitoring thread
12:18:10.949 DEBUG None o.e.f.FileWatchService - init watcher
12:18:10.950 DEBUG None o.e.f.FileWatchService - start monitoring WatchService events
12:18:10.950 DEBUG None o.e.f.FileWatchService - start a background monitoring thread
12:18:10.960 DEBUG None o.e.f.FileWatchService - start monitoring WatchService events
12:18:11.012 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Successfully bound to /127.0.0.1:34134
12:18:11.020 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
12:18:11.020 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   OS : Linux
12:18:11.021 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Java : OpenJDK 64-Bit Server VM 25.111-b14, OpenJDK Runtime Environment 1.8.0_111-b14
12:18:11.021 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Scala version: version 2.11.8
12:18:11.021 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Ensime : 1.0.0
12:18:11.032 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with Scala version: 2.11.8
12:18:11.033 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with sbt version: 0.13.11
12:18:11.033 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built from git sha: cf6a0453d3a7890b3a711769cee081b497f535b6
12:18:11.034 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built on: 2016-06-25 12:21:53.134
12:18:11.036 INFO  None o.e.s.PortUtil$ - creating port file: /home/hkr/Desarrollo/scala/TDD/hello/.ensime_cache/http
12:18:11.037 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
12:18:13.431 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - New connection accepted
12:18:13.522 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Connection from localhost
12:18:13.524 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Client connected - active clients now: 1
12:18:13.576 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/1 o.e.s.RequestHandler - ConnectionInfoReq
12:18:13.578 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq in state awaitingConnectionInfoReq
12:18:13.582 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/1 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),1.0) in state receive
12:18:13.934 INFO  None c.z.h.HikariDataSource - HikariCP pool HikariPool-0 is starting.
12:18:14.732 DEBUG None o.e.i.SearchService - findStaleFileChecks
12:18:14.744 DEBUG None o.e.i.SearchService - removing 0 stale files from the index
12:18:14.773 DEBUG None o.e.i.SearchService - Indexing bases...
12:18:14.782 DEBUG None o.e.i.SearchService - committing index to disk...
12:18:14.787 DEBUG None o.e.i.SearchService - ...done committing index
12:18:14.800 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - created 0 and removed 0 searchable rows
12:18:16.459 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state startup
```
2.  Set a breakpoint with `C-c C-d b`

```
12:19:44.347 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/5 o.e.s.RequestHandler - DebugSetBreakReq(/home/hkr/Desarrollo/scala/TDD/hello/src/main/scala/example/Hello.scala,8)
12:19:44.348 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugSetBreakReq(/home/hkr/Desarrollo/scala/TDD/hello/src/main/scala/example/Hello.scala,8) in state handleRequests
12:19:44.348 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugSetBreakReq(/home/hkr/Desarrollo/scala/TDD/hello/src/main/scala/example/Hello.scala,8)
12:19:44.350 ERROR None o.e.c.d.VirtualMachineManager - Unable to execute action with VM
java.lang.IllegalStateException: No VM active for debugging!
	at org.ensime.core.debug.VirtualMachineManager.withVM(VirtualMachineManager.scala:174)
	at org.ensime.core.debug.DebugActor.org$ensime$core$debug$DebugActor$$withVM(DebugActor.scala:319)
	at org.ensime.core.debug.DebugActor$$anonfun$receive$1.applyOrElse(DebugActor.scala:112)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:62)
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:50)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at org.ensime.core.debug.DebugActor.aroundReceive(DebugActor.scala:40)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
12:19:44.363 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/5 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:19:44.367 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/6 o.e.s.RequestHandler - DebugListBreakpointsReq
12:19:44.367 ERROR None o.e.c.d.VirtualMachineManager - Unable to execute action with VM
java.lang.IllegalStateException: No VM active for debugging!
	at org.ensime.core.debug.VirtualMachineManager.withVM(VirtualMachineManager.scala:174)
	at org.ensime.core.debug.DebugActor$$anonfun$receive$1.applyOrElse(DebugActor.scala:151)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:62)
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:50)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at org.ensime.core.debug.DebugActor.aroundReceive(DebugActor.scala:40)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
12:19:44.367 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugListBreakpointsReq in state handleRequests
12:19:44.368 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugListBreakpointsReq
12:19:44.369 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/6 o.e.s.RequestHandler - received handled message BreakpointList(List(),List()) in state receive
```

3.  Run `M-x ensime-db-attatch`

```
12:20:25.572 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/7 o.e.s.RequestHandler - DebugAttachReq(localhost,5005)
12:20:25.572 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugAttachReq(localhost,5005) in state handleRequests
12:20:25.573 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugAttachReq(localhost,5005)
12:20:25.724 INFO  None o.s.a.d.AttachingDebugger - Attaching hostname: localhost
12:20:25.724 INFO  None o.s.a.d.AttachingDebugger - Attaching port: 5005
12:20:25.724 INFO  None o.s.a.d.AttachingDebugger - Attaching timeout: 
12:20:25.775 DEBUG None o.s.a.d.AttachingDebugger - Starting looping task runner
12:20:25.948 DEBUG None o.s.a.l.ManagerContainer - Created exception request from pending ExceptionRequestInfo(2ce91ebb-cbc8-4bfc-9277-dfc40fa19d8a,false,<CATCHALL>,false,true,List(UniqueIdProperty(2ce91ebb-cbc8-4bfc-9277-dfc40fa19d8a), SuspendPolicyProperty(2)))
12:20:25.958 DEBUG None o.s.a.l.ManagerContainer - Created thread death request from pending ThreadDeathRequestInfo(2cdd6218-8d13-4cd8-ab73-17ef7c2ee5a2,false,List(UniqueIdProperty(2cdd6218-8d13-4cd8-ab73-17ef7c2ee5a2), SuspendPolicyProperty(0)))
12:20:25.960 DEBUG None o.s.a.l.ManagerContainer - Created thread start request from pending ThreadStartRequestInfo(be888464-75f2-49f3-bb9d-efdcf7eeac07,false,List(UniqueIdProperty(be888464-75f2-49f3-bb9d-efdcf7eeac07), SuspendPolicyProperty(0)))
12:20:25.961 DEBUG None o.s.a.v.StandardScalaVirtualMachine - (Scala VM 0c00217f-0443-47c2-b48a-aa9abe1e7068) Initializing Scala virtual machine!
12:20:25.962 DEBUG None o.s.a.v.StandardScalaVirtualMachine - (Scala VM 0c00217f-0443-47c2-b48a-aa9abe1e7068) Adding custom event handlers!
12:20:25.977 DEBUG None o.s.a.v.StandardScalaVirtualMachine - Processing all pending requests!
12:20:25.989 DEBUG None o.s.a.v.StandardScalaVirtualMachine - Starting low-level event manager!
12:20:25.993 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/7 o.e.s.RequestHandler - received handled message DebugVmSuccess(success) in state receive
```

At this Point the breakpoint is hit and the debugger stops at the line the breakpoint was set. 

Now run `C-c C-d n` to get to the next line, but nothing happens, I can run that command 10 times and the program does not advance:

```
12:23:32.224 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/22 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:32.225 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:32.226 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:32.228 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/22 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:33.118 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/23 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:33.118 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:33.118 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:33.121 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/23 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:33.821 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/24 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:33.822 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:33.822 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:33.824 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/24 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:34.501 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/25 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:34.502 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:34.502 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:34.504 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/25 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:35.142 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/26 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:35.142 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:35.143 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:35.144 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/26 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:35.805 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/27 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:35.806 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:35.806 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:35.807 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/27 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:36.538 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/28 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:36.539 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:36.539 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:36.541 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/28 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:37.149 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/29 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:37.150 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:37.150 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:37.151 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/29 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:37.837 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/30 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:37.838 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:37.838 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:37.840 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/30 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:38.478 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/31 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:38.478 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:38.478 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:38.481 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/31 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:39.173 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/32 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:39.174 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:39.174 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:39.175 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/32 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:39.845 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/33 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:39.846 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:39.846 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:39.847 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/33 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:40.509 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/34 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:40.510 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:40.510 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:40.511 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/34 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:44.165 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/35 o.e.s.RequestHandler - DebugContinueReq(DebugThreadId(1))
12:23:44.166 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugContinueReq(DebugThreadId(1)) in state handleRequests
12:23:44.166 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugContinueReq(DebugThreadId(1))
12:23:44.167 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/35 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:50.997 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/36 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:50.998 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:50.998 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:51.000 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/36 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:52.221 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/37 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:52.222 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:52.222 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:52.223 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/37 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:53.333 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/38 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:53.334 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:53.334 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:53.335 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/38 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:54.510 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/39 o.e.s.RequestHandler - DebugNextReq(DebugThreadId(1))
12:23:54.510 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugNextReq(DebugThreadId(1)) in state handleRequests
12:23:54.510 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugNextReq(DebugThreadId(1))
12:23:54.512 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/39 o.e.s.RequestHandler - received handled message TrueResponse in state receive
12:23:55.573 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/40 o.e.s.RequestHandler - DebugContinueReq(DebugThreadId(1))
12:23:55.574 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message DebugContinueReq(DebugThreadId(1)) in state handleRequests
12:23:55.574 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.d.DebugActor - received handled message DebugContinueReq(DebugThreadId(1))
12:23:55.574 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/40 o.e.s.RequestHandler - received handled message TrueResponse in state receive
```

### Expected behaviour

Advance to the next line in source code when debugging ( `C-c C-d n`)

### Actual behaviour

Nothing happens, The only way to advance the execution in the program is with ( `C-c C-d c`)

If you need anything else, please tell me.

Regards

**Comment by fommil** [comment]
Can you please give a reproduction in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also a good starting point. We are more than happy to help you turn it into an automated test, and discuss ideas on how to fix it. Read the http://ensime.org/contributing guide for more information.

We close tickets that look like a known issue or don't provide the details requested by the template, but it's not the end of the conversation and we will open it up again when there is enough information to go on. This is to improve the quality of our issue tracker and to make it easier for contributors to help.

We will reopen this ticket if you can confirm it is a bug by giving us a **detailed** reproduction. Please read the http://ensime.org/getting_help guide to understand the steps that are required prior to submitting a bug report.

**Comment by fommil** [comment]
I think you meant to raise this on ensime-emacs

**Comment by elbaulp** [comment]
Ups, right, I will post it in ensime-emacs. Thanks
