### ISSUE TITLE
coursier RC2 causes the server to crash

### ISSUE THREAD

**Issue by bomgar** [ensime/ensime-sbt#334]
### Steps to reproduce

1.  use coursier 1.0.0-RC2
2. run ensimeConfig
3. start ensime in emacs 

### Expected behaviour
It should work the same way it does with coursier 1.0.0-RC1

### Actual behaviour
A lot of error messages and the server terminates

```
16:36:28.136 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
16:36:28.136 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   OS : Linux
16:36:28.136 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Java : OpenJDK 64-Bit Server VM 25.121-b13, OpenJDK Runtime Environment 1.8.0_121-b13
16:36:28.137 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Scala version: version 2.11.8
16:36:28.137 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Ensime : 2.0.0-SNAPSHOT
16:36:28.137 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Heap Size : 4294967296
16:36:28.138 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with Scala version: 2.11.11
16:36:28.138 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with sbt version: 0.13.15
16:36:28.138 INFO  None o.e.s.PortUtil$ - creating port file: /home/phaun/development/projects/trade-loginservice/.ensime_cache/http
16:36:28.138 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built from git sha: 6f1cdf5d6cccd90a6bc1b5644e8b9babc8c20c8e
16:36:28.138 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built on: 2017-05-01
16:36:28.139 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1:36905
16:36:28.238 ERROR akka://ENSIME/user/ensime-main o.e.s.ServerActor - Error with monitor actor akka://ENSIME/user/ensime-main/project: exception during creation
akka.actor.ActorInitializationException: akka://ENSIME/user/ensime-main/project: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:175)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:65)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	... 9 common frames omitted
Caused by: org.apache.commons.vfs2.FileSystemException: Unknown message with code "Could not open Jar file "/home/phaun/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/websocket/websocket-api/9.2.15.v20160210/websocket-api-9.2.15.v20160210-sources.jar.asc.asc". in /home/phaun/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/websocket/websocket-api/9.2.15.v20160210/websocket-api-9.2.15.v20160210-sources.jar.asc.asc =>".
	at org.ensime.vfs.package$RichVFS$.org$ensime$vfs$RichVFS$$withContext$extension(EnsimeVFS.scala:78)
	at org.ensime.vfs.package$RichVFS$.vjar$extension(EnsimeVFS.scala:91)
	at org.ensime.indexer.SourceResolver$$anonfun$6.apply(SourceResolver.scala:90)
	at org.ensime.indexer.SourceResolver$$anonfun$6.apply(SourceResolver.scala:88)
	at scala.collection.immutable.List.map(List.scala:277)
	at org.ensime.indexer.SourceResolver.<init>(SourceResolver.scala:88)
	at org.ensime.core.Project.<init>(Project.scala:48)
	... 18 common frames omitted
Caused by: org.apache.commons.vfs2.FileSystemException: Could not open Jar file "/home/phaun/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/websocket/websocket-api/9.2.15.v20160210/websocket-api-9.2.15.v20160210-sources.jar.asc.asc".
	at org.apache.commons.vfs2.provider.jar.JarFileSystem.createZipFile(JarFileSystem.java:66)
	at org.apache.commons.vfs2.provider.zip.ZipFileSystem.getZipFile(ZipFileSystem.java:141)
	at org.apache.commons.vfs2.provider.jar.JarFileSystem.getZipFile(JarFileSystem.java:219)
	at org.apache.commons.vfs2.provider.zip.ZipFileSystem.init(ZipFileSystem.java:87)
	at org.apache.commons.vfs2.provider.AbstractVfsContainer.addComponent(AbstractVfsContainer.java:56)
	at org.apache.commons.vfs2.provider.AbstractFileProvider.addFileSystem(AbstractFileProvider.java:108)
	at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.createFileSystem(AbstractLayeredFileProvider.java:88)
	at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.findFile(AbstractLayeredFileProvider.java:61)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:804)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:760)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:709)
	at org.ensime.vfs.package$RichVFS$$anonfun$vjar$extension$1.apply(EnsimeVFS.scala:91)
	at org.ensime.vfs.package$RichVFS$$anonfun$vjar$extension$1.apply(EnsimeVFS.scala:91)
	at org.ensime.vfs.package$RichVFS$.org$ensime$vfs$RichVFS$$withContext$extension(EnsimeVFS.scala:77)
	... 24 common frames omitted
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.apache.commons.vfs2.provider.jar.JarFileSystem.createZipFile(JarFileSystem.java:62)
	... 37 common frames omitted
16:36:28.241 ERROR akka://ENSIME/user/ensime-main/project a.a.OneForOneStrategy - Unknown message with code "Could not open Jar file "/home/phaun/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/websocket/websocket-api/9.2.15.v20160210/websocket-api-9.2.15.v20160210-sources.jar.asc.asc". in /home/phaun/.coursier/c
akka.actor.ActorInitializationException: akka://ENSIME/user/ensime-main/project: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:175)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:65)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	... 9 common frames omitted
Caused by: org.apache.commons.vfs2.FileSystemException: Unknown message with code "Could not open Jar file "/home/phaun/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/websocket/websocket-api/9.2.15.v20160210/websocket-api-9.2.15.v20160210-sources.jar.asc.asc". in /home/phaun/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/websocket/websocket-api/9.2.15.v20160210/websocket-api-9.2.15.v20160210-sources.jar.asc.asc =>".
	at org.ensime.vfs.package$RichVFS$.org$ensime$vfs$RichVFS$$withContext$extension(EnsimeVFS.scala:78)
	at org.ensime.vfs.package$RichVFS$.vjar$extension(EnsimeVFS.scala:91)
	at org.ensime.indexer.SourceResolver$$anonfun$6.apply(SourceResolver.scala:90)
	at org.ensime.indexer.SourceResolver$$anonfun$6.apply(SourceResolver.scala:88)
	at scala.collection.immutable.List.map(List.scala:277)
	at org.ensime.indexer.SourceResolver.<init>(SourceResolver.scala:88)
	at org.ensime.core.Project.<init>(Project.scala:48)
	... 18 common frames omitted
Caused by: org.apache.commons.vfs2.FileSystemException: Could not open Jar file "/home/phaun/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/websocket/websocket-api/9.2.15.v20160210/websocket-api-9.2.15.v20160210-sources.jar.asc.asc".
	at org.apache.commons.vfs2.provider.jar.JarFileSystem.createZipFile(JarFileSystem.java:66)
	at org.apache.commons.vfs2.provider.zip.ZipFileSystem.getZipFile(ZipFileSystem.java:141)
	at org.apache.commons.vfs2.provider.jar.JarFileSystem.getZipFile(JarFileSystem.java:219)
	at org.apache.commons.vfs2.provider.zip.ZipFileSystem.init(ZipFileSystem.java:87)
	at org.apache.commons.vfs2.provider.AbstractVfsContainer.addComponent(AbstractVfsContainer.java:56)
	at org.apache.commons.vfs2.provider.AbstractFileProvider.addFileSystem(AbstractFileProvider.java:108)
	at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.createFileSystem(AbstractLayeredFileProvider.java:88)
	at org.apache.commons.vfs2.provider.AbstractLayeredFileProvider.findFile(AbstractLayeredFileProvider.java:61)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:804)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:760)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:709)
	at org.ensime.vfs.package$RichVFS$$anonfun$vjar$extension$1.apply(EnsimeVFS.scala:91)
	at org.ensime.vfs.package$RichVFS$$anonfun$vjar$extension$1.apply(EnsimeVFS.scala:91)
	at org.ensime.vfs.package$RichVFS$.org$ensime$vfs$RichVFS$$withContext$extension(EnsimeVFS.scala:77)
	... 24 common frames omitted
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.apache.commons.vfs2.provider.jar.JarFileSystem.createZipFile(JarFileSystem.java:62)
	... 37 common frames omitted
16:36:28.241 ERROR None Server - Shutdown requested due to internal error: Monitor actor failed with class akka.actor.ActorInitializationException - akka.actor.ActorInitializationException: akka://ENSIME/user/ensime-main/project: exception during creation
16:36:28.242 INFO  None Server - Shutting down the ActorSystem
16:36:28.242 INFO  None Server - Awaiting actor system termination

```

**Comment by fommil** [comment]
this report is basically no use without an example project that demonstrates the problem. Can you please put something up on github with the dependencies that cause a problem?

**Comment by fommil** [comment]
also, you may need to raise this as a bug with coursier, depends what @alexarchambault thinks. But we need a repro project before saying anything.

**Comment by alexarchambault** [comment]
This line shows that corresponds to what was discussed on the Gitter of coursier,
```
Caused by: org.apache.commons.vfs2.FileSystemException: Unknown message with code "Could not open Jar file "/home/phaun/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/websocket/websocket-api/9.2.15.v20160210/websocket-api-9.2.15.v20160210-sources.jar.asc.asc". in /home/phaun/.coursier/cache/v1/https/repo1.maven.org/maven2/org/eclipse/jetty/websocket/websocket-api/9.2.15.v20160210/websocket-api-9.2.15.v20160210-sources.jar.asc.asc =>".
```

Filtering the artifacts on their type should fix that.

**Comment by bomgar** [comment]
I compared the `.ensime` files. The `.asc` files are listed in `:library-sources` with the new version of coursier. With RC1 this wasn't the case.

**Comment by bomgar** [comment]
It happens with https://github.com/21re/cli-micro-tools 
The project doesn't compile with RC1 though because of a bug in coursier.

The other projects where I encounter this problem are private.

**Comment by fommil** [comment]
@alexarchambault our use of coursier is to download the ensime server. This seems to be when the user is using coursier to resolve their own dependencies. In which case we call the standard sbt API here https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/EnsimePlugin.scala#L403-L406

**Comment by fommil** [comment]
@bomgar if you don't user coursier, does ensime work ok?

**Comment by mriehl** [comment]
Hi all,

I have the same problem as @bomgar with the exact same setup.
I've tested https://github.com/21re/cli-micro-tools without coursier and it works "fine" (aside from the fact that sbt takes a bloody long time to resolve everything with ivy).

Also, removing the bintray plugin from https://github.com/21re/cli-micro-tools ensime works fine with coursier RC1 (it's due to https://github.com/coursier/coursier/issues/514)

**Comment by fommil** [comment]
hmm, this seems like a bug in coursier RC2 as far as I can tell... it's providing `.asc` files when we ask for source artifacts. @alexarchambault does that sound about right?

**Comment by fommil** [comment]
as a workaround to get @bomgar @mriehl up and running, have a look at `ensimeConfigTransformer` which lets you manually filter whatever you want.

**Comment by bomgar** [comment]
@fommil would it be a good idea to patch the ensime server so that invalid zip files are ignored? Log the error and continue with what is working?

**Comment by fommil** [comment]
@bomgar no, that just hides the fundamental problem. A core principle of ensime-server is that it fails if given bad input, rather than trying to handle all possible corner cases and then overly complicate the code. It'd also be easier from a practical point of view to just patch the `EnsimePlugin` to filter non jar/zip files in that line. I'd accept a PR to do that.

**Comment by fommil** [comment]
(you can also drop `EnsimePlugin.scala` into your `project` dir and hack around... so long as you don't break bin compat)

**Comment by alexarchambault** [comment]
When processing the list of artifacts, you should filter them on their `type` field, like done [here](https://github.com/alexarchambault/ammonium/blob/cb6efe091ea1b8fd83a65737cbb18fa4ba4d8eb1/amm/runtime/src/main/scala/ammonite/runtime/tools/DependencyThing.scala#L104).

**Comment by bomgar** [comment]
@alexarchambault the code that breaks doesn't use coursier directly. The standard sbt API returns something else when the coursier plugin is active.
```
artifactFilter(classifier = Artifact.SourceClassifier)
```
Or am I getting this wrong?
