### ISSUE TITLE
NoSuchMethodError in EnsimeCoursierPlugin

### ISSUE THREAD

**Issue by dragos** [ensime/ensime-sbt#341]
I am trying to use Ensime on https://github.com/softwaremill/scala-clippy. I'm using "sbt-ensime" % "1.12.12", and I get this on startup:

```
java.lang.NoSuchMethodError: coursier.maven.MavenRepository$.apply$default$5()Lscala/collection/immutable/Set;
	at org.ensime.EnsimeCoursierPlugin$$anonfun$buildSettings$2.apply(EnsimeCoursierPlugin.scala:55)
	at org.ensime.EnsimeCoursierPlugin$$anonfun$buildSettings$2.apply(EnsimeCoursierPlugin.scala:53)
	at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:609)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.NoSuchMethodError: coursier.maven.MavenRepository$.apply$default$5()Lscala/collection/immutable/Set;
```

**Comment by dragos** [comment]
Closing this, it turns out to be a case of PEBKAC. Works after deleting `~/.sbt/0.13/plugins/target`

**Comment by fommil** [comment]
argh, I thought all those kinds of sbt issues were long gone. Apparently not.
