### ISSUE TITLE
Jiline dep jettison unresolvable 

### ISSUE THREAD

**Issue by magnusart** [ensime/ensime-sbt#371]
### Steps to reproduce

1. Sbt 0.3.16 
2. ensime plugin
3. sbt ensimeConfig

### Expected behaviour
The task should setup the build for ensime

### Actual behaviour
Fails with error:
```
[error] ({.}/*:ensimeServerJars) failed to resolve ((org.codehaus.jettison:jettison,1.3.3),List(download 
error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: 
https://repo1.maven.org/maven2/org/codehaus/jettison/jettison/1.3.3/jettison-1.3.3.pom (Server returned 
HTTP response code: 416 for URL: 
https://repo1.maven.org/maven2/org/codehaus/jettison/jettison/1.3.3/jettison-1.3.3.pom) while 
downloading https://repo1.maven.org/maven2/org/codehaus/jettison/jettison/1.3.3/jettison-1.3.3.pom))
```
Accessing the URL directly in my browser seems to give a proper response. Error 416 would suggest that the request is invalid?

**Comment by yyadavalli** [comment]
Need more information.

sbt-ensime version
A small project reproducing the issue

**Comment by magnusart** [comment]
I've evolved the project and moved away from this particular setup but I'll give it a go in a few days to see if I can get a project setup.

**Comment by yyadavalli** [comment]
Closing till we get a reproduction

**Comment by qwertystop** [comment]
Reproduced in a brand-new `1.0` project:

```
qwertystop@dt ~/code/classwork/lspdp $ mkdir demo
qwertystop@dt ~/code/classwork/lspdp $ cd demo/
qwertystop@dt ~/code/classwork/lspdp/demo $ sbt
[warn] No sbt.version set in project/build.properties, base directory: /home/qwertystop/code/classwork/lspdp/demo
[info] Loading settings from plugins.sbt ...
[info] Loading global plugins from /home/qwertystop/.sbt/1.0/plugins
[info] Set current project to demo (in build file:/home/qwertystop/code/classwork/lspdp/demo/)
[info] sbt server started at local:///home/qwertystop/.sbt/1.0/server/84e5aaf7a516ababc8f2/sock
sbt:demo> ensimeConfig
[info] ENSIME update.
[info] Updating ...
[info] Done updating.
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-javadoc.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar ...
[info] downloading https://repo1.maven.org/maven2/jline/jline/2.14.5/jline-2.14.5-sources.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4-javadoc.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-xml_2.12;1.0.6!scala-xml_2.12.jar(src) (455ms)
[info] 	[SUCCESSFUL ] jline#jline;2.14.5!jline.jar(src) (494ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar ...
[info] downloading https://repo1.maven.org/maven2/jline/jline/2.14.5/jline-2.14.5-javadoc.jar ...
[info] 	[SUCCESSFUL ] jline#jline;2.14.5!jline.jar(doc) (469ms)
[info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-xml_2.12;1.0.6!scala-xml_2.12.jar(doc) (746ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.4/scala-compiler-2.12.4-javadoc.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.12.4!scala-reflect.jar(doc) (2499ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4-sources.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.12.4!scala-reflect.jar(src) (532ms)
[info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.12.4!scala-compiler.jar(doc) (6070ms)
[info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.12.4!scala-library.jar(doc) (7143ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.4/scala-compiler-2.12.4-sources.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-sources.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.12.4!scala-library.jar(src) (280ms)
[info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.12.4!scala-compiler.jar(src) (445ms)
[error] java.lang.RuntimeException: failed to resolve ((io.netty:netty-parent,4.1.13.Final),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom) while downloading https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom))
[error] 	at org.ensime.CoursierHelper$.$anonfun$resolve$4(CoursierHelper.scala:85)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at org.ensime.CoursierHelper$.resolve(CoursierHelper.scala:84)
[error] 	at org.ensime.CoursierHelper$.resolveEnsimeJarsImpl(CoursierHelper.scala:42)
[error] 	at org.ensime.CoursierHelper$.resolveEnsimeJars(CoursierHelper.scala:22)
[error] 	at org.ensime.EnsimeCoursierPlugin$.$anonfun$buildSettings$4(EnsimeCoursierPlugin.scala:50)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ThisBuild / ensimeServerJars) failed to resolve ((io.netty:netty-parent,4.1.13.Final),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom) while downloading https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom))
[error] Total time: 8 s, completed Jan 21, 2018 9:50:39 AM
```

Error also occurs in a preexisting `0.13` project:
```
> qwertystop@dt ~/code/classwork/lspdp/anagrams $ sbt
> [info] Loading global plugins from /home/qwertystop/.sbt/0.13/plugins
> [info] Loading project definition from /home/qwertystop/code/classwork/lspdp/anagrams/project
> [info] Set current project to anagrams (in build file:/home/qwertystop/code/classwork/lspdp/anagrams/)
> ensimeConfig
> [info] ENSIME update.
> [error] ({.}/*:ensimeServerJars) failed to resolve ((io.netty:netty-parent,4.1.13.Final),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom) while downloading https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom))
> [error] Total time: 2 s, completed Jan 21, 2018 9:52:32 AM
```

This is my first attempted use of Ensime.

**Comment by ag91** [comment]
Hi, I had the same problem. 
In my case the project is using a repositories file to redirect sbt to a custom artifactory repository. Apparently ensime-sbt does not use the repositories file by default: when I added the repositories address manually, it worked fine.

My .sbt/0.13/global.sbt file looks a bit like this:
``` scala
import org.ensime.EnsimeCoursierKeys._
import org.ensime.EnsimeKeys._

ensimeRepositoryUrls in ThisBuild += "https://artifactory.ing.net/artifactory/xxx"
ensimeRepositoryUrls in ThisBuild += "https://artifactory.ing.net/artifactory/snapshots_yyy/"
```
Hope this can help future readers with this issue.
