### ISSUE TITLE
HTTP 416 on ensimeConfig

### ISSUE THREAD

**Issue by qwertystop** [ensime/ensime-sbt#388]
`ensimeConfig` does not work. I haven't done anything beyond following the directions on the website.

### Steps to reproduce

1. `~ $ mdkir demo; cd demo`
2. `~/demo $ sbt`
3. `> ensimeConfig`

### Expected behaviour
Ensime produces necessary `.ensime` file, and correctly integrates with editor plugins from then on.

### Actual behaviour
```
[info] ENSIME update.
[info] Updating ...
[info] Done updating.
[error] java.lang.RuntimeException: failed to resolve ((io.netty:netty-parent,4.1.13.Final),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom) while downloading https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom))
[error] 	at org.ensime.CoursierHelper$.$anonfun$resolve$4(CoursierHelper.scala:85)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at org.ensime.CoursierHelper$.resolve(CoursierHelper.scala:84)
[error] 	at org.ensime.CoursierHelper$.resolveEnsimeJarsImpl(CoursierHelper.scala:42)
[error] 	at org.ensime.CoursierHelper$.resolveEnsimeJars(CoursierHelper.scala:22)
[error] 	at org.ensime.EnsimeCoursierPlugin$.$anonfun$buildSettings$4(EnsimeCoursierPlugin.scala:50)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ThisBuild / ensimeServerJars) failed to resolve ((io.netty:netty-parent,4.1.13.Final),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom) while downloading https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.13.Final/netty-parent-4.1.13.Final.pom))
[error] Total time: 2 s, completed Jan 27, 2018 11:11:05 AM
```
The same thing (HTTP 416) happens in real projects with actual content, running on sbt 0.13.

**Comment by qwertystop** [comment]
Firefox successfully receives a 200 OK and what looks at a glance like an entirely reasonable ~50 KB XML file, if I try the same URL in-browser.

**Comment by avdv** [comment]
@qwertystop, a 416 HTTP status code would suggest that you have a (stale) incomplete copy of the pom already on your system, and when trying to fetch the missing part, the server cannot satisfy the requested range.

Try to find the file and delete it, look in `~/.ivy2/cache/...`.

**Comment by qwertystop** [comment]
Deleted all of `~/.ivy2/cache/io.netty/`. Same error, on both a new 1.0 project and an existing 0.13. Tried deleting all contents of `~/.ivy2/cache`. Same error. It's always that one URL.

**Comment by avdv** [comment]
Since the stacktrace mentioned coursier, have a look in `~/.coursier/cache/...`.

**Comment by qwertystop** [comment]
Deleted `~/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-parent`. Success. Thank you.
