### ISSUE TITLE
ensimeConfig throws missing setting ensimeScalacTransformer on Lagom project

### ISSUE THREAD

**Issue by guillegr123** [ensime/ensime-sbt#401]
When running the command ensimeConfig on a [Lagom 1.4.4](https://www.lagomframework.com/documentation/1.4.x/scala/Home.html) project, I got this error:

`> ensimeConfig
[info] ENSIME update.
[info] Resolving com.lightbend.lagom#lagom-reloadable-server_2.12;1.4.4 ...
[info] ENSIME processing lagom-internal-meta-project-service-locator (lagom-internal-meta-project-service-locator)
[error] Missing setting: ensimeScalacTransformer
[trace] Stack trace suppressed: run last my-project/*:ensimeConfig for the full output.
[error] (my-project/*:ensimeConfig) java.lang.IllegalArgumentException
[error] Total time: 56 s, completed Jun 12, 2018 7:37:12 PM`

This is the full stack trace:

`> last my-project/*:ensimeConfig
java.lang.IllegalArgumentException
        at org.ensime.CommandSupport$.org$ensime$CommandSupport$$fail(EnsimePlugin.scala:812)
        at org.ensime.CommandSupport$RichSettingKey$$anonfun$gimme$1.apply(EnsimePlugin.scala:820)
        at org.ensime.CommandSupport$RichSettingKey$$anonfun$gimme$1.apply(EnsimePlugin.scala:820)
        at scala.Option.getOrElse(Option.scala:120)
        at org.ensime.CommandSupport$RichSettingKey.gimme(EnsimePlugin.scala:820)
        at org.ensime.EnsimePlugin$.org$ensime$EnsimePlugin$$configDataFor$1(EnsimePlugin.scala:527)
        at org.ensime.EnsimePlugin$$anonfun$projectData$4.apply(EnsimePlugin.scala:586)
        at org.ensime.EnsimePlugin$$anonfun$projectData$4.apply(EnsimePlugin.scala:586)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.Set$Set2.foreach(Set.scala:94)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:93)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.ensime.EnsimePlugin$.projectData(EnsimePlugin.scala:586)
        at org.ensime.EnsimePlugin$$anonfun$ensimeConfigTask$3$$anonfun$apply$14$$anonfun$apply$15$$anonfun$16.apply(EnsimePlugin.scala:371)
        at org.ensime.EnsimePlugin$$anonfun$ensimeConfigTask$3$$anonfun$apply$14$$anonfun$apply$15$$anonfun$16.apply(EnsimePlugin.scala:368)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at org.ensime.EnsimePlugin$$anonfun$ensimeConfigTask$3$$anonfun$apply$14$$anonfun$apply$15.apply(EnsimePlugin.scala:368)
        at org.ensime.EnsimePlugin$$anonfun$ensimeConfigTask$3$$anonfun$apply$14$$anonfun$apply$15.apply(EnsimePlugin.scala:321)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (my-project/*:ensimeConfig) java.lang.IllegalArgumentException`

It seems that the project `lagom-internal-meta-project-service-locator` is created dynamically by the Lagom plugin on build, as it is located under *target/lagom-dynamic-projects*.

Can I ignore the project?
Or can I add the missing setting on my build.sbt file? If so, how and what should I add?

**Comment by fommil** [comment]
please raise it with Lightbend. If they are not going to support ensime through their commercial subscription, we sure as hell aren't going to support their code through our volunteer efforts.

**Comment by lightwave** [comment]
ensime/ensime-sbt#401

**Comment by asauray** [comment]
The issue can be fixed by manually adding the missing configuration to your build.sbt or your global.sbt.

```
import org.ensime.EnsimeKeys._
import org.ensime.EnsimePlugin

ensimeIgnoreMissingDirectories := true

ensimeIgnoreScalaMismatch in ThisBuild := true
ensimeScalaVersion in ThisBuild := "2.12.6"

lazy val serviceLocatorProject = ProjectRef(uri("."), "lagom-internal-meta-project-service-locator")
ensimeUnmanagedSourceArchives in serviceLocatorProject := Nil
ensimeUnmanagedJavadocArchives in serviceLocatorProject := Nil
ensimeScalacTransformer in serviceLocatorProject := identity
ensimeScalacOptions in serviceLocatorProject := EnsimePlugin.ensimeSuggestedScalacOptions(scalaVersion.value)
ensimeJavacOptions in serviceLocatorProject := Nil

lazy val cassandraProject = ProjectRef(uri("."), "lagom-internal-meta-project-cassandra")
ensimeUnmanagedSourceArchives in cassandraProject := Nil
ensimeUnmanagedJavadocArchives in cassandraProject := Nil
ensimeScalacTransformer in cassandraProject := identity
ensimeScalacOptions in cassandraProject := EnsimePlugin.ensimeSuggestedScalacOptions(scalaVersion.value)
ensimeJavacOptions in cassandraProject := Nil

lazy val kafkaProject = ProjectRef(uri("."), "lagom-internal-meta-project-kafka")
ensimeUnmanagedSourceArchives in kafkaProject := Nil
ensimeUnmanagedJavadocArchives in kafkaProject := Nil
ensimeScalacTransformer in kafkaProject := identity
ensimeScalacOptions in kafkaProject := EnsimePlugin.ensimeSuggestedScalacOptions(scalaVersion.value)
ensimeJavacOptions in kafkaProject := Nil
```
